# Generated by Django 2.2 on 2021-12-15 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20211215_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutorder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Customer'),
        ),
    ]
